; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; ===== Setup 정보 =====
[Setup]
PrivilegesRequired=admin
; 설치할 애플리케이션 이름 및 버전
AppName=캐논7092 설치프로그램
AppVersion=1.0
; 기본 설치 경로 (예: Program Files\MyPrinterInstaller)
DefaultDirName={pf}\Canon7000Installer
; 출력 파일 이름 (빌드 후 생성되는 Setup.exe 파일의 이름)
OutputBaseFilename=캐논7092 설치프로그램
; 설치 완료 후 프로그램 추가/제거에 등록
UninstallDisplayIcon={app}\캐논7092 설치프로그램

; ===== 설치 옵션 =====
; 설치 완료 후 바로 실행 여부 등 추가 옵션들을 설정할 수 있습니다.
Compression=lzma
SolidCompression=yes

; ===== 파일 복사 =====
[Files]
; 단일 EXE 파일 (PyInstaller로 만든 실행 파일)
Source: "dist\install_end.exe"; DestDir: "{app}"; Flags: ignoreversion
; printers.json 파일 복사
Source: "printers.json"; DestDir: "{app}"; Flags: ignoreversion
; 추가 폴더 전체 복사 (하위 폴더 모두 포함)
Source: "Driver\*"; DestDir: "{app}\Driver"; Flags: recursesubdirs createallsubdirs
Source: "DrvSetup\*"; DestDir: "{app}\DrvSetup"; Flags: recursesubdirs createallsubdirs
Source: "IJPAT\*"; DestDir: "{app}\IJPAT"; Flags: recursesubdirs createallsubdirs
Source: "LANUTIL\*"; DestDir: "{app}\LANUTIL"; Flags: recursesubdirs createallsubdirs
Source: "SCNUTIL\*"; DestDir: "{app}\SCNUTIL"; Flags: recursesubdirs createallsubdirs

; ===== 바로 가기 생성 =====
[Icons]
; 시작 메뉴 바로 가기
; Name: "{commonprograms}\MyPrinterInstaller"; Filename: "{app}\install_end.exe"
; 바탕화면 바로 가기를 원하면 주석 해제
Name: "{commondesktop}\캐논7092 설치프로그램"; Filename: "{app}\install_end.exe"
